### 1. 서울시의 전체 지리 정보를 저장합니다.
POST http://localhost:8082/regions
Content-Type: application/json
Accept-Charset: utf-8

{
  "name": "서울시",
  "area": [
    {
      "x": 126.835,
      "y": 37.688
    },
    {
      "x": 127.155,
      "y": 37.702
    },
    {
      "x": 127.184,
      "y": 37.474
    },
    {
      "x": 126.821,
      "y": 37.454
    },
    {
      "x": 126.835,
      "y": 37.688
    }
  ]
}

### 2. 과천시의 전체 지리 정보를 저장합니다.
POST http://localhost:8082/regions
Content-Type: application/json
Accept-Charset: utf-8

{
  "name": "과천시",
  "area": [
    {
      "x": 126.998,
      "y": 37.463
    },
    {
      "x": 127.028,
      "y": 37.436
    },
    {
      "x": 126.992,
      "y": 37.403
    },
    {
      "x": 126.965,
      "y": 37.421
    },
    {
      "x": 126.998,
      "y": 37.463
    }
  ]
}

### 3. 의정부시의 전체 지리 정보를 저장합니다.
POST http://localhost:8082/regions
Content-Type: application/json
Accept-Charset: utf-8

{
  "name": "의정부시",
  "area": [
    {
      "x": 127.025,
      "y": 37.766
    },
    {
      "x": 127.096,
      "y": 37.766
    },
    {
      "x": 127.099,
      "y": 37.724
    },
    {
      "x": 127.035,
      "y": 37.705
    },
    {
      "x": 127.020,
      "y": 37.742
    },
    {
      "x": 127.025,
      "y": 37.766
    }

  ]
}


### 4. 관심 지역 북한산의 전체 지리 정보를 저장합니다.
POST http://localhost:8082/aois
Content-Type: application/json
Accept-Charset: utf-8

{
  "name": "북한산",
  "area": [
    {
      "x": 127.02,
      "y": 37.742
    },
    {
      "x": 127.023,
      "y": 37.664
    },
    {
      "x": 126.945,
      "y": 37.605
    },
    {
      "x": 126.962,
      "y": 37.692
    },
    {
      "x": 127.02,
      "y": 37.742
    }
  ]
}

### 5. 관심 지역 관악산의 전체 지리 정보를 저장합니다.
POST http://localhost:8082/aois
Content-Type: application/json
Accept-Charset: utf-8

{
  "name": "관악산",
  "area": [
    {
      "x": 126.985,
      "y": 37.464
    },
    {
      "x": 126.980,
      "y": 37.429
    },
    {
      "x": 126.933,
      "y": 37.406
    },
    {
      "x": 126.910,
      "y": 37.432
    },
    {
      "x": 126.931,
      "y": 37.456
    },
    {
      "x": 126.985,
      "y": 37.464
    }
  ]
}

### 6.행정지역에 지리적으로 포함되는 관심지역을 조회합니다.
GET http://localhost:8082/regions/1/aois/intersects
Accept: application/json

> {%
  client.test("Region Id를 활용하여 행정지역에 지리적으로 포함되는 관심지역을 조회합니다. ", function() {
      client.assert(response.status === 200, "Response status is not 200")
  })
 %}

### 7.특정 좌표에 가장 가까운 관심지역을 조회합니다.
GET http://localhost:8082/aois?lat=127.026993&long=37.497933
Accept: application/json

> {%
  client.test("latitude와 longitude 활용하여 특정 좌표에 가장 가까운 관심지역을 조회합니다. ", function() {
      client.assert(response.status === 200, "Response status is not 200")
  })
 %}